<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <PublisherName>ahmedayman4a</PublisherName>
    <PackageId>Linkedin Learning Courses Downloader</PackageId>
    <Product>Linkedin Learning Courses Downloader</Product>
    <Authors>ahmedayman4a</Authors>
    <Copyright>2021</Copyright>
    <Version>1.2</Version>
    <AssemblyName>Linkedin Learning Courses Downloader</AssemblyName>
    <ApplicationIcon>linked-learning-favicon.ico</ApplicationIcon>
    <Description>Download LinkedIn Learning courses with exercise files and transcripts</Description>
    <PackageIcon>linked-learning-favicon.ico</PackageIcon>

  <TargetLatestRuntimePatch>true</TargetLatestRuntimePatch>
    <GenerateResourceMSBuildArchitecture>CurrentArchitecture</GenerateResourceMSBuildArchitecture>
    <GenerateResourceMSBuildRuntime>CurrentRuntime</GenerateResourceMSBuildRuntime>
    <Platforms>AnyCPU</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LLCD.CourseExtractor\LLCD.CourseExtractor.csproj" />
    <ProjectReference Include="..\LLCD.DownloaderConfig\LLCD.DownloaderConfig.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="ShellProgressBar">
      <HintPath>Assemblies\ShellProgressBar.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Include="linked-learning-favicon.ico">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Portable.BouncyCastle" Version="1.9.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="10.0.8" />
  </ItemGroup>

</Project>
